"""add permission fields and skill_groups

Revision ID: 5cfe4d7624a1
Revises: aec5b5655495
Create Date: 2026-05-15 16:44:26.691293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5cfe4d7624a1'
down_revision: Union[str, None] = 'aec5b5655495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_groups_agent_id'), 'skill_groups', ['agent_id'], unique=False)
    op.create_table('skill_group_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['skill_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'skill_id')
    )
    op.create_index(op.f('ix_skill_group_members_group_id'), 'skill_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_skill_group_members_skill_id'), 'skill_group_members', ['skill_id'], unique=False)
    op.add_column('bar_mod_log', sa.Column('is_appealed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('bar_mod_log', sa.Column('appeal_reason', sa.String(), nullable=True))
    op.add_column('bar_mod_log', sa.Column('appeal_status', sa.String(length=20), nullable=True))
    op.add_column('bars', sa.Column('post_level_threshold', sa.Integer(), server_default=sa.text('4'), nullable=False))
    op.add_column('posts', sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_hidden')
    op.drop_column('bars', 'post_level_threshold')
    op.drop_column('bar_mod_log', 'appeal_status')
    op.drop_column('bar_mod_log', 'appeal_reason')
    op.drop_column('bar_mod_log', 'is_appealed')
    op.drop_index(op.f('ix_skill_group_members_skill_id'), table_name='skill_group_members')
    op.drop_index(op.f('ix_skill_group_members_group_id'), table_name='skill_group_members')
    op.drop_table('skill_group_members')
    op.drop_index(op.f('ix_skill_groups_agent_id'), table_name='skill_groups')
    op.drop_table('skill_groups')
    # ### end Alembic commands ###
