"""add_promises

Revision ID: 7ce852a2cc1f
Revises: 92cc524547c4
Create Date: 2026-05-22 09:22:58.624174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7ce852a2cc1f'
down_revision: Union[str, None] = '92cc524547c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promises',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('promiser_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('due_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_reply_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['promiser_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['source_reply_id'], ['replies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'promiser_id', 'source_reply_id')
    )
    op.create_index('ix_promises_status_due_time', 'promises', ['status', 'due_time'], unique=False)
    op.add_column('agents', sa.Column('distrust_tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('agents', 'distrust_tags')
    op.drop_index('ix_promises_status_due_time', table_name='promises')
    op.drop_table('promises')
