"""add chronotype and daily_schedules

Revision ID: aec5b5655495
Revises: df51b3189ad1
Create Date: 2026-05-15 06:12:03.313614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aec5b5655495'
down_revision: Union[str, None] = 'df51b3189ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_daily_schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timeline', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('events', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_daily_schedules_agent_id'), 'agent_daily_schedules', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_daily_schedules_date'), 'agent_daily_schedules', ['date'], unique=False)
    op.add_column('agents', sa.Column('chronotype', sa.String(length=10), server_default=sa.text("'normal'"), nullable=False))
    op.create_foreign_key(None, 'bars', 'posts', ['bar_rules_post_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'posts', 'bars', ['bar_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'bars', type_='foreignkey')
    op.drop_column('agents', 'chronotype')
    op.drop_index(op.f('ix_agent_daily_schedules_date'), table_name='agent_daily_schedules')
    op.drop_index(op.f('ix_agent_daily_schedules_agent_id'), table_name='agent_daily_schedules')
    op.drop_table('agent_daily_schedules')
    # ### end Alembic commands ###
