"""initial_schema

Revision ID: df51b3189ad1
Revises: 
Create Date: 2026-05-14 10:40:45.433161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = 'df51b3189ad1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('income_level', sa.String(length=20), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('school_or_company', sa.String(length=200), nullable=True),
    sa.Column('boarding', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('interests', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('personality_vector', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('life_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_settings', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('stealth_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_online', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_identity', sa.UUID(), nullable=True),
    sa.Column('solidified_memories', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['previous_identity'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slangs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.Column('usage', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_slangs_status'), 'slangs', ['status'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('injected_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_category'), 'topics', ['category'], unique=False)
    op.create_index(op.f('ix_topics_fetched_at'), 'topics', ['fetched_at'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_agent_id'), 'activity_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_event_type'), 'activity_logs', ['event_type'], unique=False)
    op.create_table('agent_schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('active_windows', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('browse_speed', sa.String(length=10), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('reply_impulse', sa.Float(), nullable=False),
    sa.Column('max_flow_rounds', sa.Integer(), nullable=False),
    sa.Column('max_flow_per_day', sa.Integer(), nullable=False),
    sa.Column('weekly_boost', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('calendar_events', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('agent_slangs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('slang_id', sa.Integer(), nullable=False),
    sa.Column('personal_affinity', sa.Float(), nullable=False),
    sa.Column('learned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['slang_id'], ['slangs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'slang_id')
    )
    op.create_index(op.f('ix_agent_slangs_agent_id'), 'agent_slangs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_slangs_slang_id'), 'agent_slangs', ['slang_id'], unique=False)
    op.create_table('bars',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('current_owner_id', sa.UUID(), nullable=False),
    sa.Column('member_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('post_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('level_titles', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bar_rules_post_id', sa.UUID(), nullable=True),
    sa.Column('is_sage_managed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bar_rules_post_id'], ['posts.id'], use_alter=True),
    sa.ForeignKeyConstraint(['creator_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['current_owner_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('follows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followed_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id')
    )
    op.create_index(op.f('ix_follows_followed_id'), 'follows', ['followed_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=10), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('bar_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('urge_type', sa.String(length=50), nullable=True),
    sa.Column('is_essential', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_rule_post', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('essential_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('like_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inspiration', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_bar_id'), 'posts', ['bar_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_is_essential'), 'posts', ['is_essential'], unique=False)
    op.create_index(op.f('ix_posts_is_pinned'), 'posts', ['is_pinned'], unique=False)
    op.create_table('private_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_messages_recipient_id'), 'private_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_private_messages_sender_id'), 'private_messages', ['sender_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('attitude', sa.String(length=20), server_default=sa.text("'neutral'"), nullable=False),
    sa.Column('intimacy', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'target_id')
    )
    op.create_index(op.f('ix_relationships_agent_id'), 'relationships', ['agent_id'], unique=False)
    op.create_index(op.f('ix_relationships_intimacy'), 'relationships', ['intimacy'], unique=False)
    op.create_index(op.f('ix_relationships_target_id'), 'relationships', ['target_id'], unique=False)
    op.create_table('agent_bar_level',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('bar_id', sa.UUID(), nullable=False),
    sa.Column('exp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('checkin_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_checkin_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'bar_id')
    )
    op.create_index(op.f('ix_agent_bar_level_agent_id'), 'agent_bar_level', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_bar_level_bar_id'), 'agent_bar_level', ['bar_id'], unique=False)
    op.create_table('bar_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('bar_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'member'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_muted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'bar_id')
    )
    op.create_index(op.f('ix_bar_members_agent_id'), 'bar_members', ['agent_id'], unique=False)
    op.create_index(op.f('ix_bar_members_bar_id'), 'bar_members', ['bar_id'], unique=False)
    op.create_table('bar_mod_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bar_id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bar_mod_log_bar_id'), 'bar_mod_log', ['bar_id'], unique=False)
    op.create_index(op.f('ix_bar_mod_log_created_at'), 'bar_mod_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_bar_mod_log_moderator_id'), 'bar_mod_log', ['moderator_id'], unique=False)
    op.create_table('bar_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bar_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bar_rules_bar_id'), 'bar_rules', ['bar_id'], unique=False)
    op.create_index(op.f('ix_bar_rules_is_current'), 'bar_rules', ['is_current'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'post_id')
    )
    op.create_index(op.f('ix_bookmarks_agent_id'), 'bookmarks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_post_id'), 'bookmarks', ['post_id'], unique=False)
    op.create_table('elections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bar_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('target_agent_id', sa.UUID(), nullable=False),
    sa.Column('initiator_id', sa.UUID(), nullable=False),
    sa.Column('declaration_post_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('votes_for', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('votes_against', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('voting_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['declaration_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elections_bar_id'), 'elections', ['bar_id'], unique=False)
    op.create_index(op.f('ix_elections_status'), 'elections', ['status'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'post_id')
    )
    op.create_index(op.f('ix_likes_post_id'), 'likes', ['post_id'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_reply_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['parent_reply_id'], ['replies.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replies_author_id'), 'replies', ['author_id'], unique=False)
    op.create_index(op.f('ix_replies_created_at'), 'replies', ['created_at'], unique=False)
    op.create_index(op.f('ix_replies_post_id'), 'replies', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_post_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_created_at'), table_name='replies')
    op.drop_index(op.f('ix_replies_author_id'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_likes_post_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('ix_elections_status'), table_name='elections')
    op.drop_index(op.f('ix_elections_bar_id'), table_name='elections')
    op.drop_table('elections')
    op.drop_index(op.f('ix_bookmarks_post_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_agent_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_bar_rules_is_current'), table_name='bar_rules')
    op.drop_index(op.f('ix_bar_rules_bar_id'), table_name='bar_rules')
    op.drop_table('bar_rules')
    op.drop_index(op.f('ix_bar_mod_log_moderator_id'), table_name='bar_mod_log')
    op.drop_index(op.f('ix_bar_mod_log_created_at'), table_name='bar_mod_log')
    op.drop_index(op.f('ix_bar_mod_log_bar_id'), table_name='bar_mod_log')
    op.drop_table('bar_mod_log')
    op.drop_index(op.f('ix_bar_members_bar_id'), table_name='bar_members')
    op.drop_index(op.f('ix_bar_members_agent_id'), table_name='bar_members')
    op.drop_table('bar_members')
    op.drop_index(op.f('ix_agent_bar_level_bar_id'), table_name='agent_bar_level')
    op.drop_index(op.f('ix_agent_bar_level_agent_id'), table_name='agent_bar_level')
    op.drop_table('agent_bar_level')
    op.drop_index(op.f('ix_relationships_target_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_intimacy'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_agent_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_private_messages_sender_id'), table_name='private_messages')
    op.drop_index(op.f('ix_private_messages_recipient_id'), table_name='private_messages')
    op.drop_table('private_messages')
    op.drop_index(op.f('ix_posts_is_pinned'), table_name='posts')
    op.drop_index(op.f('ix_posts_is_essential'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_bar_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_followed_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_table('bars')
    op.drop_index(op.f('ix_agent_slangs_slang_id'), table_name='agent_slangs')
    op.drop_index(op.f('ix_agent_slangs_agent_id'), table_name='agent_slangs')
    op.drop_table('agent_slangs')
    op.drop_table('agent_schedules')
    op.drop_index(op.f('ix_activity_logs_event_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_agent_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_topics_fetched_at'), table_name='topics')
    op.drop_index(op.f('ix_topics_category'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_slangs_status'), table_name='slangs')
    op.drop_table('slangs')
    op.drop_table('agents')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS vector")
